[package]
name = "rust-rtow"
version = "0.1.0"
authors = ["velvetops <quantumular@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
rayon = "1.1.0"
